### PR TITLE
Feature - Allow setting the service name

### PR DESCRIPTION
**Pull request by CptLemming**
Add a method to specify a service name, while keeping the default as the supplied hostname.

### CODE REVIEW

**Comment by ssilverman** [comment]
What is your use case for this? Do you actually need the names to be different?

**Comment by CptLemming** [comment]
Sure, sorry I should have included more information.

I'm using a Teensy + ethernet adaptor to expose a websocket via MDNS. The host name and service name are both utilised by the consuming service and are not the same.

This is an example I'm trying to replicate:

```
$ avahi-browse -r _calrec-node._tcp
pri-aoip IPv4 UR6500-70B3D5042C85-0-sec-5                   _calrec-node._tcp    local
   hostname = [UR6500-70B3D5042C85-0-sec-2.local]
   address = [192.168.30.12]
   port = [50002]
   txt = ["version=0.4"]
```

I recently switched over from using the `NativeEthernet` library that also offered the ability to set different host / service names.

**Comment by ssilverman** [comment]
Thanks for that. I think there needs to be a few more changes for this than are in the PR, so I'm going to go ahead and make them myself. Specifically:
1. I'd prefer the docs match the current style. I intend to reorder some of the sentences you added.
2. The service name should be specified per service added, not for every service.
3. Additionally, I want to think about the API a little bit more.

Would you mind creating an issue for this and reference this PR? I'll track the changes in there. Thanks again for the request.

**Comment by ssilverman** [comment]
I'll add: if you need the changes right away, feel free to clone or fork the repo and use that for now.

**Comment by ssilverman** [comment]
See if you like this change: 4c2c999

**Comment by ssilverman** [comment]
Closing because the feature was added here: https://github.com/ssilverman/QNEthernet/commit/4c2c999289c906764132b9bb22f1ba77c482d629

**Pull request closed without merging**
